# replicaCount: 1

# image:
#   repository: langfuse/langfuse
#   pullPolicy: Always
#   tag: 3

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

langfuse:
  port: 3000
  # nodeEnv: production
  # next:
  #   healthcheckBasePath: ""
  nextauth:
    url: https://expert-langfuse-nonprod.internal.towerswatson.com
    secret: changeme
  salt: changeme2
  #licenseKey: ""
  telemetryEnabled: True
  # nextPublicSignUpDisabled: False
  # enableExperimentalFeatures: False
  # extraContainers: []
  # extraVolumes: []
  # extraInitContainers: []
  # extraVolumeMounts: []

  web:
    resources: {}
    # hpa:
    #   enabled: false
    #   minReplicas: 1
    #   maxReplicas: 2
    #   targetCPUUtilizationPercentage: 50
    # vpa:
    #   enabled: false
    #   controlledResources: []
    #   maxAllowed: {}
    #   minAllowed: {}
    #   updatePolicy:
    #     updateMode: Auto
  worker:
    resources: {}
    # hpa:
    #   enabled: false
    #   minReplicas: 1
    #   maxReplicas: 2
    #   targetCPUUtilizationPercentage: 50
    # vpa:
    #   enabled: false
    #   controlledResources: []
    #   maxAllowed: {}
    #   minAllowed: {}
    #   updatePolicy:
    #     updateMode: Auto

  additionalEnv:
    # REDIS
    - name: "REDIS_CONNECTION_STRING"
      value: "redis://default:changeme@langfuse-valkey-master:6379/0"
    # CLICKHOUSE
    - name: "CLICKHOUSE_MIGRATION_URL"
      value: "clickhouse://langfuse-clickhouse:9000"
    - name: "CLICKHOUSE_URL"
      value: "http://langfuse-clickhouse:8123"
    - name: "CLICKHOUSE_USER"
      value: "default"
    - name: "CLICKHOUSE_PASSWORD"
      value: "changeme"
    # S3 / MinIO
    - name: "LANGFUSE_S3_EVENT_UPLOAD_ENABLED"
      value: "true"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_BUCKET"
      value: "langfuse"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_REGION"
      value: "auto"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID"
      value: "minio"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY"
      value: "miniosecret"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT"
      value: "http://langfuse-minio:9000"
    - name: "LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE"
      value: "true"
    # Azure AD SSO - pending use keyvault/secured resource to store values
    - name: AUTH_AZURE_AD_CLIENT_ID
      value: "f160f1f4-554a-4775-a14c-108af88f655e"
    - name: AUTH_AZURE_AD_CLIENT_SECRET
      value: "Rgu8Q~YpXnebcAZPIjMsaRwB3W52YnR8TJNggbGc"
    - name: AUTH_AZURE_AD_TENANT_ID
      value: "76e3921f-489b-4b7e-9547-9ea297add9b5"
    - name: AUTH_DISABLE_USERNAME_PASSWORD
      value: "true"

# serviceAccount:
#   create: true
#   annotations: {}
#   name: ""

# podAnnotations: {}

# podSecurityContext: {}

# securityContext: {}

service:
  type: ClusterIP
  port: 3000
  nodePort: ""

ingress:
  enabled: true
  className: traefik
  tls:
    - hosts:
      - expert-langfuse-nonprod.internal.towerswatson.com
      secretName: internal-wildcard-cert
  hosts:
    - host: expert-langfuse-nonprod.internal.towerswatson.com
      paths: 
        - path: /
          pathType: Prefix

# resources: {}

# nodeSelector: {}

# tolerations: []

# affinity: {}

postgresql:
  host: langfuse-postgresql
  auth:
    username: postgres
    password: postgres
    database: postgres_langfuse
  deploy: true
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432

clickhouse:
  deploy: true
  shards: 1 # Fixed. Langfuse does not support multi-shard clusters.
  replicaCount: 3
  resourcesPreset: none
  resources:
    limits:
      cpu: "2"
      memory: 6Gi
    requests:
      cpu: "1"
      memory: 4Gi
  auth:
    username: default
    password: changeme

valkey:
  deploy: true
  architecture: standalone
  primary:
    extraFlags:
      - "--maxmemory-policy noeviction"
  auth:
    password: changeme

minio:
  deploy: true
  defaultBuckets: 'langfuse'
  auth:
    rootUser: 'minio'
    rootPassword: 'miniosecret'

extraManifests: []